// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/v1/data_store.proto

package v1

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SaveRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveRequest) Reset()         { *m = SaveRequest{} }
func (m *SaveRequest) String() string { return proto.CompactTextString(m) }
func (*SaveRequest) ProtoMessage()    {}
func (*SaveRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db092b1f88678f70, []int{0}
}

func (m *SaveRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveRequest.Unmarshal(m, b)
}
func (m *SaveRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveRequest.Marshal(b, m, deterministic)
}
func (m *SaveRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveRequest.Merge(m, src)
}
func (m *SaveRequest) XXX_Size() int {
	return xxx_messageInfo_SaveRequest.Size(m)
}
func (m *SaveRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SaveRequest proto.InternalMessageInfo

func (m *SaveRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SaveRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type SaveReply struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveReply) Reset()         { *m = SaveReply{} }
func (m *SaveReply) String() string { return proto.CompactTextString(m) }
func (*SaveReply) ProtoMessage()    {}
func (*SaveReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_db092b1f88678f70, []int{1}
}

func (m *SaveReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveReply.Unmarshal(m, b)
}
func (m *SaveReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveReply.Marshal(b, m, deterministic)
}
func (m *SaveReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveReply.Merge(m, src)
}
func (m *SaveReply) XXX_Size() int {
	return xxx_messageInfo_SaveReply.Size(m)
}
func (m *SaveReply) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveReply.DiscardUnknown(m)
}

var xxx_messageInfo_SaveReply proto.InternalMessageInfo

func (m *SaveReply) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SaveReply) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type LoadRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadRequest) Reset()         { *m = LoadRequest{} }
func (m *LoadRequest) String() string { return proto.CompactTextString(m) }
func (*LoadRequest) ProtoMessage()    {}
func (*LoadRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_db092b1f88678f70, []int{2}
}

func (m *LoadRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadRequest.Unmarshal(m, b)
}
func (m *LoadRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadRequest.Marshal(b, m, deterministic)
}
func (m *LoadRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadRequest.Merge(m, src)
}
func (m *LoadRequest) XXX_Size() int {
	return xxx_messageInfo_LoadRequest.Size(m)
}
func (m *LoadRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoadRequest proto.InternalMessageInfo

func (m *LoadRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type LoadReply struct {
	Value                string   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoadReply) Reset()         { *m = LoadReply{} }
func (m *LoadReply) String() string { return proto.CompactTextString(m) }
func (*LoadReply) ProtoMessage()    {}
func (*LoadReply) Descriptor() ([]byte, []int) {
	return fileDescriptor_db092b1f88678f70, []int{3}
}

func (m *LoadReply) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoadReply.Unmarshal(m, b)
}
func (m *LoadReply) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoadReply.Marshal(b, m, deterministic)
}
func (m *LoadReply) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoadReply.Merge(m, src)
}
func (m *LoadReply) XXX_Size() int {
	return xxx_messageInfo_LoadReply.Size(m)
}
func (m *LoadReply) XXX_DiscardUnknown() {
	xxx_messageInfo_LoadReply.DiscardUnknown(m)
}

var xxx_messageInfo_LoadReply proto.InternalMessageInfo

func (m *LoadReply) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*SaveRequest)(nil), "data_store.SaveRequest")
	proto.RegisterType((*SaveReply)(nil), "data_store.SaveReply")
	proto.RegisterType((*LoadRequest)(nil), "data_store.LoadRequest")
	proto.RegisterType((*LoadReply)(nil), "data_store.LoadReply")
}

func init() {
	proto.RegisterFile("proto/v1/data_store.proto", fileDescriptor_db092b1f88678f70)
}

var fileDescriptor_db092b1f88678f70 = []byte{
	// 194 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x2c, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x2f, 0x33, 0xd4, 0x4f, 0x49, 0x2c, 0x49, 0x8c, 0x2f, 0x2e, 0xc9, 0x2f, 0x4a, 0xd5,
	0x03, 0x8b, 0x09, 0x71, 0x21, 0x44, 0x94, 0x4c, 0xb9, 0xb8, 0x83, 0x13, 0xcb, 0x52, 0x83, 0x52,
	0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84, 0x04, 0xb8, 0x98, 0xb3, 0x53, 0x2b, 0x25, 0x18, 0x15, 0x18,
	0x35, 0x38, 0x83, 0x40, 0x4c, 0x21, 0x11, 0x2e, 0xd6, 0xb2, 0xc4, 0x9c, 0xd2, 0x54, 0x09, 0x26,
	0xb0, 0x18, 0x84, 0xa3, 0x64, 0xcc, 0xc5, 0x09, 0xd1, 0x56, 0x90, 0x53, 0x49, 0xb4, 0x26, 0x79,
	0x2e, 0x6e, 0x9f, 0xfc, 0xc4, 0x14, 0x9c, 0x76, 0x29, 0x29, 0x72, 0x71, 0x42, 0x14, 0x80, 0x4c,
	0x85, 0x9b, 0xc1, 0x88, 0x64, 0x86, 0x51, 0x3d, 0x17, 0xa7, 0x4b, 0x62, 0x49, 0x62, 0x30, 0xc8,
	0xf1, 0x42, 0x16, 0x5c, 0x2c, 0x20, 0x57, 0x08, 0x89, 0xeb, 0x21, 0xf9, 0x11, 0xc9, 0x3b, 0x52,
	0xa2, 0x98, 0x12, 0x05, 0x39, 0x95, 0x4a, 0x0c, 0x20, 0x9d, 0x20, 0x9b, 0x50, 0x75, 0x22, 0x39,
	0x0e, 0x55, 0x27, 0xdc, 0x51, 0x4a, 0x0c, 0x4e, 0x6c, 0x51, 0x2c, 0x7a, 0xfa, 0x65, 0x86, 0x49,
	0x6c, 0xe0, 0xb0, 0x34, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0xc7, 0xa2, 0xfd, 0x0e, 0x68, 0x01,
	0x00, 0x00,
}
