"""initial migration

Revision ID: 6fd914b623ca
Revises: 
Create Date: 2023-02-12 13:22:04.930362

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6fd914b623ca"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "publishers",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_publishers_id"), "publishers", ["id"], unique=False)
    op.create_index(op.f("ix_publishers_name"), "publishers", ["name"], unique=False)
    op.create_table(
        "books",
        sa.Column("id", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("author", sa.String(), nullable=True),
        sa.Column("year", sa.Integer(), nullable=True),
        sa.Column("publisher_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["publisher_id"],
            ["publishers.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_books_author"), "books", ["author"], unique=False)
    op.create_index(op.f("ix_books_id"), "books", ["id"], unique=False)
    op.create_index(op.f("ix_books_title"), "books", ["title"], unique=False)
    op.create_index(op.f("ix_books_year"), "books", ["year"], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_books_year"), table_name="books")
    op.drop_index(op.f("ix_books_title"), table_name="books")
    op.drop_index(op.f("ix_books_id"), table_name="books")
    op.drop_index(op.f("ix_books_author"), table_name="books")
    op.drop_table("books")
    op.drop_index(op.f("ix_publishers_name"), table_name="publishers")
    op.drop_index(op.f("ix_publishers_id"), table_name="publishers")
    op.drop_table("publishers")
    # ### end Alembic commands ###
