# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: v3/person.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x0fv3/person.proto\x1a\x13v1/data_store.proto\x1a\x19google/protobuf/any.proto"\xa1\x03\n\x06Person\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x12\n\x05\x65mail\x18\x03 \x01(\tH\x01\x88\x01\x01\x12\r\n\x05phone\x18\x05 \x03(\t\x12\x0e\n\x06height\x18\x06 \x01(\x01\x12\x17\n\x06gender\x18\x07 \x01(\x0e\x32\x07.Gender\x12)\n\x08metadata\x18\x08 \x03(\x0b\x32\x17.data_store.SaveRequest\x12#\n\x05\x65xtra\x18\t \x01(\x0b\x32\x14.google.protobuf.Any\x12\r\n\x03ssn\x18\n \x01(\tH\x00\x12\x12\n\x08passport\x18\x0b \x01(\tH\x00\x12\x1f\n\x04tags\x18\x0c \x03(\x0b\x32\x11.Person.TagsEntry\x12#\n\x06values\x18\r \x03(\x0b\x32\x13.Person.ValuesEntry\x1a+\n\tTagsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\x1a\x35\n\x0bValuesEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x15\n\x05value\x18\x02 \x01(\x0e\x32\x06.Value:\x02\x38\x01\x42\n\n\x08identityB\x08\n\x06_email*\x1a\n\x05Value\x12\x08\n\x04GOOD\x10\x00\x12\x07\n\x03\x42\x41\x44\x10\x01*-\n\x06Gender\x12\x08\n\x04MALE\x10\x00\x12\n\n\x06\x46\x45MALE\x10\x01\x12\r\n\tNONBINARY\x10\x02\x42\x06Z\x04./v3b\x06proto3'
)

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "v3.person_pb2", globals())
if _descriptor._USE_C_DESCRIPTORS == False:

    DESCRIPTOR._options = None
    DESCRIPTOR._serialized_options = b"Z\004./v3"
    _PERSON_TAGSENTRY._options = None
    _PERSON_TAGSENTRY._serialized_options = b"8\001"
    _PERSON_VALUESENTRY._options = None
    _PERSON_VALUESENTRY._serialized_options = b"8\001"
    _VALUE._serialized_start = 487
    _VALUE._serialized_end = 513
    _GENDER._serialized_start = 515
    _GENDER._serialized_end = 560
    _PERSON._serialized_start = 68
    _PERSON._serialized_end = 485
    _PERSON_TAGSENTRY._serialized_start = 365
    _PERSON_TAGSENTRY._serialized_end = 408
    _PERSON_VALUESENTRY._serialized_start = 410
    _PERSON_VALUESENTRY._serialized_end = 463
# @@protoc_insertion_point(module_scope)
