global:
  evaluation_interval: 15s
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets:
          - localhost:9080

# remote_write:
#   - url: http://localhost:1234
