global:
  evaluation_interval: 15s
  scrape_interval: 15s

scrape_configs:
  - job_name: localhost
    file_sd_configs:
      - files:
          - ./targets/*.yml

  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        port: 9323
        refresh_interval: 15s

    relabel_configs:
      - source_labels:
          - __meta_docker_container_name
        regex: ^/?(.*)$
        target_label: container_name
