global:
  evaluation_interval: 15s
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093

scrape_configs:
  - job_name: localhost
    file_sd_configs:
      - files:
          - ./targets/*.yml

  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        port: 9323
        refresh_interval: 15s

    relabel_configs:
      - source_labels:
          - __meta_docker_container_name
        regex: ^/?(.*)$
        target_label: container_name
      - source_labels:
          - __meta_docker_network_ip
        target_label: container_ip
      - source_labels:
          - __meta_docker_container_network_mode
        target_label: container_network_mode
      - source_labels:
          - __meta_docker_container_id
        action: hashmod
        modulus: 1000000
        target_label: container_id
      - source_labels:
          - __meta_docker_port_private
        target_label: container_port

  - job_name: "federate"
    scrape_interval: 15s

    honor_labels: true
    metrics_path: "/federate"

    params:
      "match[]":
        - '{job="prometheus"}'
        - '{__name__=~"job:.*"}'

    static_configs:
      - targets:
          - localhost:9080

  - job_name: "dynamics"
    http_sd_configs:
      - url: http://localhost:1323
        refresh_interval: "60s"

  - job_name: "ory"
    metrics_path: /metrics/prometheus
    file_sd_configs:
      - files:
          - ./targets/oathkeeper.yml
          - ./targets/kratos.yml

rule_files:
  - ./rules/*.alerts.yml
  - ./rules/*.rules.yml

tracing:
  endpoint: http://localhost:9411/api/v2/spans

remote_read:
  - url: http://localhost:9080/api/v1/read
    remote_timeout: "1m"
    read_recent: false
    follow_redirects: true
