global:
  evaluation_interval: 15s
  scrape_interval: 15s

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093

scrape_configs:
  - job_name: localhost
    file_sd_configs:
      - files:
          - ./targets/*.yml

  - job_name: docker
    docker_sd_configs:
      - host: unix:///var/run/docker.sock
        port: 9323
        refresh_interval: 15s

    relabel_configs:
      - source_labels:
          - __meta_docker_container_name
        regex: ^/?(.*)$
        target_label: container_name
      - source_labels:
          - __meta_docker_network_ip
        target_label: container_ip
      - source_labels:
          - __meta_docker_container_network_mode
        target_label: container_network_mode
      - source_labels:
          - __meta_docker_container_id
        action: hashmod
        modulus: 1000000
        target_label: container_id
      - source_labels:
          - __meta_docker_port_private
        target_label: container_port


rule_files:
  - ./rules/*.alerts.yml
  - ./rules/*.rules.yml

tracing:
  endpoint: http://localhost:9411/api/v2/spans
