access_rules:
  matching_strategy: regexp
  repositories:
    - file://./ory/oathkeeper/rules/rules-bookstore.yml
authenticators:
  anonymous:
    config:
      subject: guest
    enabled: true
  bearer_token:
    config:
      check_session_url: http://localhost:40500/jwt
      force_method: GET
      forward_http_headers:
        - cookie
      preserve_path: true
      preserve_query: true
      token_from:
        header: authorization
    enabled: true
  cookie_session:
    config:
      check_session_url: http://localhost:40900/sessions/whoami
      extra_from: "@this"
      # only:
      #   - ory_kratos_session
      forward_http_headers:
        - X-Session-Token
      preserve_path: true
      subject_from: identity.id
    enabled: true
  jwt:
    config:
      allowed_algorithms:
        - RS256
        - HS256
        - RS384
      jwks_urls:
        - http://localhost:40500/.well-known/jwks.json
      required_scope:
        - openid
        - offline
      scope_strategy: hierarchic
      trusted_issuers:
        - http://localhost:40500
        - http://127.0.0.1:40500
    enabled: true
  noop:
    enabled: true
  unauthorized:
    enabled: true
authorizers:
  allow:
    enabled: true
  deny:
    enabled: true
  remote_json:
    config:
      payload: ""
      remote: http://localhost:40720/relation-tuples/check
    enabled: true
errors:
  fallback:
    - json
  handlers:
    json:
      config:
        verbose: true
        when:
          - error:
              - forbidden
      enabled: true
    redirect:
      config:
        return_to_query_param: return_to
        to: http://localhost:4455/login
        when:
          - error:
              - unauthorized
      enabled: true
log:
  leak_sensitive_values: true
  level: debug
mutators:
  header:
    config:
      headers:
        X-Email: "{{ print .Extra.identity.traits.email }}"
    enabled: true
  noop:
    enabled: true
serve:
  api:
    port: 4456
  prometheus:
    port: 9550
  proxy:
    port: 4457
tracing:
  provider: jaeger
  providers:
    jaeger:
      local_agent_address: 127.0.0.1:6831
      sampling:
        server_url: http://localhost:5778/sampling
  service_name: Ory Oathkeeper
