# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import data_store_pb2 as data__store__pb2
import grpc


class DataStoreStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Save = channel.unary_unary(
            "/data_store.DataStore/Save",
            request_serializer=data__store__pb2.SaveRequest.SerializeToString,
            response_deserializer=data__store__pb2.SaveReply.FromString,
        )
        self.Load = channel.unary_unary(
            "/data_store.DataStore/Load",
            request_serializer=data__store__pb2.LoadRequest.SerializeToString,
            response_deserializer=data__store__pb2.LoadReply.FromString,
        )


class DataStoreServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Save(self, request, context):
        """Save a key value pair"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Load(self, request, context):
        """Get a value by key"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_DataStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "Save": grpc.unary_unary_rpc_method_handler(
            servicer.Save,
            request_deserializer=data__store__pb2.SaveRequest.FromString,
            response_serializer=data__store__pb2.SaveReply.SerializeToString,
        ),
        "Load": grpc.unary_unary_rpc_method_handler(
            servicer.Load,
            request_deserializer=data__store__pb2.LoadRequest.FromString,
            response_serializer=data__store__pb2.LoadReply.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "data_store.DataStore", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))


# This class is part of an EXPERIMENTAL API.
class DataStore(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Save(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/data_store.DataStore/Save",
            data__store__pb2.SaveRequest.SerializeToString,
            data__store__pb2.SaveReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )

    @staticmethod
    def Load(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/data_store.DataStore/Load",
            data__store__pb2.LoadRequest.SerializeToString,
            data__store__pb2.LoadReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
        )
