name: rust-linter
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout
      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy, rustfmt
      # - name: Set up mold
      #   uses: rui314/setup-mold@v1
      - name: Clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: "--all --all-targets -- -D warnings"
          working-directory: ./rust
      - name: Format
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: "--all -- --check"
          working-directory: ./rust
